### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by drug007** [ANtlord/gdb-ddemangle#3]
File "~/.gdb/gdb-ddemangle/ddemangle.py", line 27
    print(f'{YELLOW}{HELP_MESSAGE}{END}')

**Comment by ANtlord** [comment]
What the version of the python do you use?

**Comment by drug007** [comment]
```
(gdb) python print(sys.version)
3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170516]
(gdb)
```

**Comment by ANtlord** [comment]
Oh my bad. F-strings is a feature of 3.6. I'm going to fix in several minutes

**Comment by ANtlord** [comment]
Fixed

**Comment by drug007** [comment]
Confirmed.
